Fix: build on NixOS without nixpkgs in the Nix path

diff --git a/server/autobuild b/server/autobuild
--- a/server/autobuild
+++ b/server/autobuild
@@ -389,6 +389,10 @@ os_nixos() {
     if [ -n "$DRY_RUN" ]; then
         return 0
     fi
+    if ! nix-instantiate --eval -E "<nixpkgs>" &>/dev/null; then
+      echo "File 'nixpkgs' was not found in the Nix path. Using NixOS/nixpkgs"
+      NIX_PATH="nixpkgs=https://github.com/nixos/nixpkgs/archive/master.tar.gz:$NIX_PATH"
+    fi
     command="AUTOBUILD_NIX_SHELL=true"
     command="$command;export AUTOBUILD_NIX_SHELL"
     command="$command;$(quote "$0" "$@")"
